/*
 * NewArmylistNameDialog.java
 *
 * Created on 21 May 2003, 11:35
 */

package org.jArmyTool.gui.components;

import org.jArmyTool.data.database.GameSystemAccessBean;
import javax.swing.*;
/**
 *
 * @author  pasleh
 */
public class NewArmylistNameDialog extends javax.swing.JDialog {
    private MainWindow main;
    
    /** Creates new form NewArmylistNameDialog */
    public NewArmylistNameDialog(java.awt.Frame parent, boolean modal, MainWindow main) {
        super(parent, modal);
        this.main = main;
        initComponents();
        
        DefaultComboBoxModel gameSystems = new DefaultComboBoxModel();
        String [] gameSystemNames = GameSystemAccessBean.getInstance().getGameSystemNames();
        for(int i = 0; i < gameSystemNames.length; ++i){
            gameSystems.addElement(gameSystemNames[i]);
        }
        this.gameSystemsCombo.setModel(gameSystems);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        armylistNameField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        gameSystemsCombo = new javax.swing.JComboBox();
        cancelButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("New Armylist Name Dialog");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        armylistNameField.setText("new armylist name");
        armylistNameField.setMinimumSize(new java.awt.Dimension(100, 23));
        armylistNameField.setPreferredSize(new java.awt.Dimension(200, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(armylistNameField, gridBagConstraints);

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(gameSystemsCombo, gridBagConstraints);

        cancelButton.setText("Forget it");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(cancelButton, gridBagConstraints);

        pack();
    }//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);        
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.main.newArmylistNameDialogReturn(this.armylistNameField.getText(), (String)this.gameSystemsCombo.getSelectedItem());
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField armylistNameField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox gameSystemsCombo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
    
}
