/*
 * OneModelStatsPanel.java
 *
 * Created on 30 November 2003, 00:58
 */

package core_src.src.org.jArmyTool.gui.components;

import java.util.Collection;
import java.util.Iterator;
import javax.swing.JLabel;
import org.jArmyTool.data.dataBeans.armylist.ArmylistModel;
import org.jArmyTool.data.dataBeans.util.ModelStat;
import org.jArmyTool.data.dataBeans.util.ModelStatHolder;
import org.jArmyTool.data.dataBeans.util.StatType;

/**
 *
 * @author  pasi
 */
public class OneModelStatsPanel extends javax.swing.JPanel {
    
    private ArmylistModel model;
    
    /** Creates new form OneModelStatsPanel */
    public OneModelStatsPanel(ArmylistModel model) {
        this.model = model;
        initComponents();
        
        
        this.initStats();
    }
    
    private void initStats(){
        StatType type = this.model.getArmylistArmy().getGameSystem().getStatType(this.model.getStatTypeName());
        
        Collection coll = type.getAllStats();
        Iterator headers = coll.iterator();
        this.statsPanel.setLayout(new java.awt.GridLayout(2, coll.size(), 2, 2));
        
        
        
        Iterator stats = this.model.getStats().iterator();
        while(headers.hasNext()){
            ModelStat headerEl = ((ModelStat)headers.next());
            String header = headerEl.getSymbol();
            String toolTip = headerEl.getTooltip();
            JLabel headerL = new JLabel(header);
            headerL.setToolTipText(toolTip);
            headerL.setFont(new java.awt.Font("Dialog", 1, 9));
            this.statsPanel.add(headerL);
        }
        
        while(stats.hasNext()){
            String value = ((ModelStatHolder)stats.next()).getValue();
            JLabel valueL = new JLabel(value);
            valueL.setFont(new java.awt.Font("Dialog", 0, 9));
            this.statsPanel.add(valueL);
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        statsPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        add(statsPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel statsPanel;
    // End of variables declaration//GEN-END:variables
    
}
