/*
 * OneModelUpdatesExpanded.java
 *
 * Created on 10 November 2003, 22:18
 */

package core_src.src.org.jArmyTool.gui.components;

import java.util.Iterator;
import java.util.LinkedList;
import org.jArmyTool.data.dataBeans.army.Model;
import org.jArmyTool.data.dataBeans.army.ModelUpdate;
import org.jArmyTool.gui.components.ModelUpdatePanel;

/**
 *
 * @author  pasi
 */
public class OneModelUpdatesExpanded extends javax.swing.JPanel {
    
    private Model model;
    
    private OneModelPanel parent;      
    private OneModelWargearPanel wgpanel;
    private LinkedList modelUpdatePanels;
    
    /** Creates new form OneModelUpdatesExpanded */
    public OneModelUpdatesExpanded(Model model, OneModelPanel parent) {
        this.modelUpdatePanels = new LinkedList();
        this.model = model;
        this.parent = parent;        
        initComponents();
        this.initUpdates();
        this.initWG();
    }
    
    private void initUpdates(){
        Iterator iterator = this.model.getUpdates().iterator();

        this.modelUpdatesPanel.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints = null;
        int x = 0;
        int y = 0;
        while(iterator.hasNext()){
            ModelUpdate modelUpdate = (ModelUpdate)iterator.next();
            ModelUpdatePanel updatePanel = new ModelUpdatePanel(modelUpdate, this.parent);
            this.modelUpdatePanels.add(updatePanel);
            if(x > 1){
                x = 0;
                ++y;
            }
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = x;
            gridBagConstraints.gridy = y;
            gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
            gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
            
            this.modelUpdatesPanel.add(updatePanel, gridBagConstraints);
            
            ++x;
        } 
    }
    
    private void initWG(){
        if(this.model.getArmylistModel().getAllowedWargear() == 0)
            return;
        this.wgpanel = new OneModelWargearPanel(this, this.model);
        this.wargearPanel.add(this.wgpanel);
    }
    
    public void refreshPointcost(){
        this.parent.refreshPointcost();
        this.parent.refrashParentPointcost();
    }
    
    public void refresUpdatePointcosts(){
        Iterator iterator = this.modelUpdatePanels.iterator();
        while(iterator.hasNext()){
            ((ModelUpdatePanel)iterator.next()).refreshPointcost();
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        modelUpdatesPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        wargearPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.add(modelUpdatesPanel, java.awt.BorderLayout.WEST);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        wargearPanel.setLayout(new java.awt.BorderLayout());

        jPanel3.add(wargearPanel, java.awt.BorderLayout.WEST);

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel modelUpdatesPanel;
    private javax.swing.JPanel wargearPanel;
    // End of variables declaration//GEN-END:variables
    
}
