/*
 * WargearPopup.java
 *
 * Created on 18 January 2003, 20:48
 */

package core_src.src.org.jArmyTool.gui.components;

import java.util.*;
import org.jArmyTool.data.dataBeans.armylist.*;
import org.jArmyTool.data.dataBeans.army.*;
import javax.swing.*;
import java.awt.*;
import org.jArmyTool.gui.listeners.*;
import org.jArmyTool.gui.components.*;
/**
 *
 * @author  pasi
 */
public class WargearPopup extends javax.swing.JFrame {
    
    private ArmylistArmy army;
    private Model model;
    private ModelPanel modelPanel;
    
    /** Creates new form WargearPopup */
    public WargearPopup(ArmylistArmy army, Model model, ModelPanel modelPanel) {
        this.army = army;
        this.model = model;
        this.modelPanel = modelPanel;
        initComponents();
        this.initWargear();
    }
    
    private void initWargear(){
        Iterator iterator = this.model.getArmylistModel().getAllowedWargearGroups().iterator();
        while(iterator.hasNext()){
            ArmylistWargearGroup temp = this.army.getWargearGroupbyName((String)iterator.next());
            this.initWargearGroup(temp, this.model.getSelectedWargear(temp.getName()));
        }
        
    }
    
    public void refreshPointcost(){
        this.modelPanel.refreshPointcost();
    }
    
    private void initWargearGroup(ArmylistWargearGroup group, Collection selected){
        JPanel panel = new JPanel(new BorderLayout());
        JPanel header = new JPanel();
        header.add(new JLabel(group.getName()));
        panel.add(header, BorderLayout.NORTH);
        JPanel main = new JPanel();
        
        Iterator iterator = group.getItems().iterator();
        while(iterator.hasNext()){
            ArmylistWargearItem temp = (ArmylistWargearItem)iterator.next();
            JCheckBox box = new JCheckBox(temp.getName(), selected.contains(temp));
            box.addActionListener(new WargearChangelistener(this.model, group.getName(), temp, this)); 
            main.add(box);
        }
        panel.add(main, BorderLayout.CENTER);
        this.wargearPanel.add(panel);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        wargearPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setText("Wargear");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        getContentPane().add(wargearPanel, java.awt.BorderLayout.CENTER);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeHandler(evt);
            }
        });

        jPanel2.add(closeButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void closeHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeHandler
        this.exit();
    }//GEN-LAST:event_closeHandler
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.exit();
    }//GEN-LAST:event_exitForm
    
    private void exit(){
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //new WargearPopup().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel wargearPanel;
    private javax.swing.JButton closeButton;
    // End of variables declaration//GEN-END:variables
    
}
