/*
 * WargearEditorMainWindow.java
 *
 * Created on 20 May 2003, 16:23
 */

package plugins_src.org.jarmytoolplugins.newarmylisteditorplugin.wargearEditor.components;

import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import org.jArmyTool.data.dataBeans.armylist.*;
import org.jarmytoolplugins.newarmylisteditorplugin.wargearEditor.engine.WargearEditorGUICore;

import java.util.*;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.StringTokenizer;
import javax.swing.JScrollBar;
import javax.swing.table.*;
import org.jArmyTool.internaldata.GUICommands;
import org.jarmytoolplugins.newarmylisteditorplugin.wargearEditor.util.WargearGroupTextField;


/**
 *
 * @author  pasleh
 */
public class WargearEditorMainWindow extends javax.swing.JFrame {

    private ArmylistArmy armylistArmy; 
    private WargearEditorGUICore core;
    
    private LinkedList itemPanels;
    /** Creates new form WargearEditorMainWindow */
    public WargearEditorMainWindow(ArmylistArmy armylistArmy, WargearEditorGUICore core) {
        this.itemPanels = new LinkedList();
        this.core = core;
        this.armylistArmy = armylistArmy;
        initComponents();
        this.initData();
        
        this.scrollPane.addMouseWheelListener(new MouseWheelListener(){
            public void mouseWheelMoved(MouseWheelEvent e){
                
                JScrollBar sb = scrollPane.getVerticalScrollBar();
                sb.setValue(sb.getValue() + (e.getWheelRotation() * GUICommands.getInstance().getWheelSteps()) );
            }
        });
    }
    
    private void initData(){
        this.itemsPanel.setLayout(new org.jarmytoolplugins.newarmylisteditorplugin.util.VerticalFlowLayout());
        this.groupsPanel.setLayout(new org.jarmytoolplugins.newarmylisteditorplugin.util.VerticalFlowLayout());
        Iterator iterator = this.armylistArmy.getWargearGroups().iterator();
        
        while(iterator.hasNext()){
            ArmylistWargearGroup wgGroup = (ArmylistWargearGroup)iterator.next();
            String groupName = wgGroup.getName();
            Iterator gIterator = wgGroup.getItems().iterator();
            
            while(gIterator.hasNext()){
                ArmylistWargearItem item = (ArmylistWargearItem)gIterator.next();
                WargearItemPanel panel = new WargearItemPanel(this.armylistArmy, wgGroup, item, this);
                this.itemsPanel.add(panel);
                this.itemPanels.add(panel);
            }
            
            
            this.groupsPanel.add(new WargearGroupTextField(wgGroup, this));
        }
    }
    
    
    
    public void saveData(){
        Iterator iterator = this.itemPanels.iterator();
        while(iterator.hasNext()){
            ((WargearItemPanel)iterator.next()).saveData();
        }
    }
    
    public void remove(WargearItemPanel panel){
        this.itemPanels.remove(panel);
        this.itemsPanel.remove(panel);
        this.itemsPanel.updateUI();
    }
    
    private void addNewItem(){
        if(this.armylistArmy.getWargearGroups().size() <= 0)
            return;
        
        ArmylistWargearItem newItem = new ArmylistWargearItem("no name", this.armylistArmy);
        ArmylistWargearGroup group = (ArmylistWargearGroup)this.armylistArmy.getWargearGroups().iterator().next();
        
        group.addItem(newItem);
        
        WargearItemPanel panel = new WargearItemPanel(this.armylistArmy, group, newItem, this);
        this.itemsPanel.add(panel);
        this.itemPanels.add(panel);
        
        JScrollBar sb = this.scrollPane.getVerticalScrollBar();
        sb.setValue(sb.getMaximum());
        this.itemsPanel.updateUI();
    }

    public void refreshGroups(){
        this.saveData();
        Iterator iterator = this.itemPanels.iterator();
        while(iterator.hasNext()){
            ((WargearItemPanel)iterator.next()).refreshGroups();
        }        
    }
    
    public void removeGroup(WargearGroupTextField field){
        this.groupsPanel.remove(field);
        this.armylistArmy.removeargearGroup(field.getGroup());
        this.groupsPanel.updateUI();
        this.refreshGroups();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        newWargearButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        groupsPanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        itemsPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Wargear Editor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        newWargearButton.setText("new item");
        newWargearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWargearButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(newWargearButton, gridBagConstraints);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBorder(new javax.swing.border.TitledBorder("Wargear Groups"));
        jButton1.setText("new group");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel5.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel5.add(groupsPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jPanel5, gridBagConstraints);

        jPanel2.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel2, java.awt.BorderLayout.EAST);

        scrollPane.setViewportView(itemsPanel);

        jPanel1.add(scrollPane, java.awt.BorderLayout.CENTER);

        titlePanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel1.setText(" Name");
        jLabel1.setMaximumSize(new java.awt.Dimension(250, 24));
        jLabel1.setMinimumSize(new java.awt.Dimension(250, 24));
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 24));
        jPanel4.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel2.setText("Points");
        jLabel2.setMaximumSize(new java.awt.Dimension(50, 24));
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 24));
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 24));
        jPanel4.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel3.setText(" Group");
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 24));
        jLabel3.setMinimumSize(new java.awt.Dimension(200, 24));
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 24));
        jPanel4.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel4.setText(" Weapons");
        jPanel4.add(jLabel4);

        titlePanel.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel1.add(titlePanel, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArmylistWargearGroup newGroup = new ArmylistWargearGroup("no name");
        this.armylistArmy.addWargearGroup(newGroup);
        this.groupsPanel.add(new WargearGroupTextField(newGroup, this));
        this.groupsPanel.updateUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void newWargearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWargearButtonActionPerformed
        this.addNewItem();
    }//GEN-LAST:event_newWargearButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.core.closeWindow();
    }//GEN-LAST:event_exitForm

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel groupsPanel;
    private javax.swing.JPanel itemsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton newWargearButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
    
}
