/*
 * WargearGroupPanel.java
 *
 * Created on 12 February 2004, 16:38
 */

package org.jarmytoolplugins.newarmylisteditorplugin.wargearEditor.components;

import org.jArmyTool.data.dataBeans.armylist.ArmylistWargearGroup;

/**
 *
 * @author  pasi
 */
public class WargearGroupPanel extends javax.swing.JPanel {
    
    private ArmylistWargearGroup group;
    private WargearEditorMainWindow parent;
    
    
    /** Creates new form WargearGroupPanel */
    public WargearGroupPanel(ArmylistWargearGroup group, WargearEditorMainWindow parent) {
        this.group = group;
        this.parent = parent;
        initComponents();
        this.initData();
    }
    
    private void initData(){
        if(group.getName() == null)
            group.setName("no name");
        this.nameField.setText(group.getName());
    }
    
    public void saveData(){
        this.group.setName(this.nameField.getText());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        nameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        setBorder(new javax.swing.border.TitledBorder("Wargear Group"));
        nameField.setText("jTextField1");
        nameField.setPreferredSize(new java.awt.Dimension(250, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(nameField, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel1.setText("Group Name: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jLabel1, gridBagConstraints);

        deleteButton.setText("del");
        deleteButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(deleteButton, gridBagConstraints);

    }//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        this.parent.deleteCurrentGroup();
    }//GEN-LAST:event_deleteButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
    
}
