/*
 * WeaponTypePanel.java
 *
 * Created on 14 October 2003, 16:14
 */

package plugins_src.org.jarmytoolplugins.newarmylisteditorplugin.weaponeditor.components;

import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.jArmyTool.data.dataBeans.armylist.ArmylistWeapon;

import org.jArmyTool.data.dataBeans.util.WeaponProfile;

/**
 *
 * @author  pasleh
 */
public class WeaponTypePanel extends javax.swing.JPanel {
    
    private Collection armylistWeapons;
    private WeaponProfile profile;
    private DefaultTableModel model;
    
    /** Creates new form WeaponTypePanel */
    public WeaponTypePanel(WeaponProfile profile, Collection armylistWeapons) {
        this.armylistWeapons = armylistWeapons;
        this.profile = profile;
        initComponents();
        this.nameLabel.setText(this.profile.getName()+":");
        this.initTable();
    }
    
    
    private void initTable(){
        
        Vector profileVector = new Vector(this.profile.getHeaders());
        profileVector.add(0, "Name");
        this.model = new DefaultTableModel(profileVector, 0);
        Iterator iterator = this.armylistWeapons.iterator();
        while(iterator.hasNext()){
            ArmylistWeapon weapon = (ArmylistWeapon)iterator.next();
            Vector vector = new Vector(weapon.getStats());
            vector.add(0, weapon.getName() );
            
            this.model.addRow(vector);
        }
        this.jTable1.setModel(this.model);
    }
    
    public WeaponProfile getWeaponProfile(){
        return this.profile;
    }
    
    public Collection getWeapons(){
        this.jTable1.editCellAt(0,0);
        LinkedList list = new LinkedList();
        Iterator tableIterator = this.model.getDataVector().iterator();
        while(tableIterator.hasNext()){
            Iterator rowIterator = ((Vector)tableIterator.next()).iterator();
            if(!rowIterator.hasNext())
                continue;
            
            String name = rowIterator.next().toString();
            if(name == null || name.length() <= 0)
                continue;
            ArmylistWeapon weapon = new ArmylistWeapon(name, this.profile);
            
            while(rowIterator.hasNext()){
                Object cell = rowIterator.next();
                try{
                    if(cell == null || ((String)cell).length() == 0)
                        cell = " ";
                }catch(ClassCastException e){
                    cell = " ";
                }
                weapon.addStat(cell.toString());
            }
            list.add(weapon);
        }
        
        return list;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        headerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        dataPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        controlPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        headerPanel.setLayout(new java.awt.BorderLayout());

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameLabel.setText("name");
        jPanel1.add(nameLabel);

        headerPanel.add(jPanel1, java.awt.BorderLayout.WEST);

        add(headerPanel, java.awt.BorderLayout.NORTH);

        dataPanel.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        dataPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(dataPanel, java.awt.BorderLayout.CENTER);

        addButton.setText("Add New Weapon");
        addButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        controlPanel.add(addButton);

        add(controlPanel, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Vector newRow = new Vector();
        newRow.add("");
        
        
        this.model.addRow(newRow);
    }//GEN-LAST:event_addButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
    
}
