/*
 * ArmylistEditorModelUpdatePanel.java
 *
 * Created on 28 October 2003, 00:25
 */

package org.jarmytoolplugins.newarmylisteditorplugin.components;

import java.util.Iterator;
import org.jArmyTool.data.dataBeans.armylist.ArmylistUnitUpdate;
import org.jArmyTool.data.dataBeans.armylist.ArmylistWeapon;
import org.jarmytoolplugins.newarmylisteditorplugin.components.WeaponPanel;

/**
 *
 * @author  pasi
 */
public class ArmylistEditorUnitUpdatePanel extends javax.swing.JPanel {
    
    private ArmylistUnitUpdate update;
    private ArmylistEditorUnitPanel unitPanel;
    private WeaponPanel weaponPanel;
    
    /** Creates new form ArmylistEditorModelUpdatePanel */
    public ArmylistEditorUnitUpdatePanel(ArmylistUnitUpdate update, ArmylistEditorUnitPanel unitPanel) {
        this.unitPanel = unitPanel;
        this.update = update;
        initComponents();
        this.initData();
    }
    
    private void initData(){
        this.nameField.setText(this.update.getName());
        
        
        if(this.update.getPointcost() == (int)this.update.getPointcost()){
            this.pointcostField.setText(""+(int)this.update.getPointcost());
        }else{
            this.pointcostField.setText(""+this.update.getPointcost());
        }
        
        
        this.pointcostPerModelCheckbox.setSelected(this.update.isPointcostPerModel());
        this.minCounterSpinner.setValue(new Integer(this.update.getMinCount()));
        this.maxCounterSpinner.setValue(new Integer(this.update.getMaxCount()));
        this.defaultCounterSpinner.setValue(new Integer(this.update.getDefaultCount()));
        
        if(!this.update.getWeapons().isEmpty()){
            this.showWeaponList();
        }
    }
    
    public void saveData(){
        this.update.setName(this.nameField.getText());
        try{
            this.update.setPointcost(Double.parseDouble(this.pointcostField.getText()));
        }catch(NumberFormatException e){}
        this.update.setPointcostPerModel(this.pointcostPerModelCheckbox.isSelected());
        
        this.update.setMinCount( ((Integer)this.minCounterSpinner.getValue()).intValue() );
        this.update.setMaxCount( ((Integer)this.maxCounterSpinner.getValue()).intValue() );
        this.update.setDefaultCount( ((Integer)this.defaultCounterSpinner.getValue()).intValue() );
        
        if(this.weaponPanel != null){
            this.update.emptyWeapons();
            Iterator iterator = this.weaponPanel.getSelectedWeapons().iterator();
            while(iterator.hasNext()){
                this.update.addWeapon((String)iterator.next());
            }            
        }        
    }
    
    public ArmylistUnitUpdate getUnitUpdate(){
        return this.update;
    }
    
    private void showWeaponList(){
        this.weaponPanelPanel.remove(this.isWeaponBoxPanel);
        this.weaponPanel = new WeaponPanel( this.unitPanel.getArmylistArmy(), this.update.getWeapons(), this.update.getName());
        this.weaponPanelPanel.add(this.weaponPanel);
        this.weaponPanelPanel.updateUI();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        weaponPanelPanel = new javax.swing.JPanel();
        isWeaponBoxPanel = new javax.swing.JPanel();
        isWeaponCheckBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        minCounterSpinner = new javax.swing.JSpinner();
        maxCounterSpinner = new javax.swing.JSpinner();
        defaultCounterSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pointcostField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pointcostPerModelCheckbox = new javax.swing.JCheckBox();
        delButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        weaponPanelPanel.setLayout(new java.awt.BorderLayout());

        isWeaponCheckBox.setText("is weapon");
        isWeaponCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isWeaponCheckBoxActionPerformed(evt);
            }
        });

        isWeaponBoxPanel.add(isWeaponCheckBox);

        weaponPanelPanel.add(isWeaponBoxPanel, java.awt.BorderLayout.CENTER);

        add(weaponPanelPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        dataPanel.setLayout(new java.awt.GridBagLayout());

        nameField.setFont(new java.awt.Font("Dialog", 1, 14));
        nameField.setText("jTextField1");
        nameField.setMaximumSize(new java.awt.Dimension(200, 23));
        nameField.setMinimumSize(new java.awt.Dimension(200, 23));
        nameField.setPreferredSize(new java.awt.Dimension(200, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        dataPanel.add(nameField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        dataPanel.add(minCounterSpinner, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        dataPanel.add(maxCounterSpinner, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        dataPanel.add(defaultCounterSpinner, gridBagConstraints);

        jLabel1.setText("min");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        dataPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("max");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        dataPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setText("default");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        dataPanel.add(jLabel3, gridBagConstraints);

        pointcostField.setText("jTextField1");
        pointcostField.setMaximumSize(new java.awt.Dimension(30, 23));
        pointcostField.setMinimumSize(new java.awt.Dimension(30, 23));
        pointcostField.setPreferredSize(new java.awt.Dimension(30, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        dataPanel.add(pointcostField, gridBagConstraints);

        jLabel4.setText("points");
        dataPanel.add(jLabel4, new java.awt.GridBagConstraints());

        pointcostPerModelCheckbox.setText("per model");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        dataPanel.add(pointcostPerModelCheckbox, gridBagConstraints);

        delButton.setText("del");
        delButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        dataPanel.add(delButton, gridBagConstraints);

        jPanel1.add(dataPanel, java.awt.BorderLayout.WEST);

        add(jPanel1, java.awt.BorderLayout.NORTH);

    }//GEN-END:initComponents

    private void isWeaponCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isWeaponCheckBoxActionPerformed
        this.saveData();
        this.showWeaponList();
    }//GEN-LAST:event_isWeaponCheckBoxActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        this.unitPanel.removeUnitUpdate(this);
    }//GEN-LAST:event_delButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dataPanel;
    private javax.swing.JSpinner defaultCounterSpinner;
    private javax.swing.JButton delButton;
    private javax.swing.JPanel isWeaponBoxPanel;
    private javax.swing.JCheckBox isWeaponCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner maxCounterSpinner;
    private javax.swing.JSpinner minCounterSpinner;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField pointcostField;
    private javax.swing.JCheckBox pointcostPerModelCheckbox;
    private javax.swing.JPanel weaponPanelPanel;
    // End of variables declaration//GEN-END:variables
    
}
