/*
 * ArmylistEditorLinkedModelPanel.java
 *
 * Created on 30 October 2003, 21:04
 */

package org.jarmytoolplugins.newarmylisteditorplugin.components;

import org.jArmyTool.data.dataBeans.armylist.ArmylistModel;
import org.jArmyTool.internaldata.GUICommands;

/**
 *
 * @author  pasi
 */
public class ArmylistEditorLinkedModelPanel extends javax.swing.JPanel {
    
    private ArmylistModel model;
    private ArmylistEditorUnitPanel unitPanel;
    
    /** Creates new form ArmylistEditorLinkedModelPanel */
    public ArmylistEditorLinkedModelPanel(ArmylistModel model, ArmylistEditorUnitPanel unitPanel) {
        this.model = model;
        this.unitPanel = unitPanel;
        initComponents();
        this.modelNamePanel.setText(this.model.getName());
        this.moveDownButton.setIcon(GUICommands.getInstance().getMovedDownArrow());
        this.moveUpButton.setIcon(GUICommands.getInstance().getMoveUpArrow());
    }
    
    public ArmylistModel getModel(){
        return this.model;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        basicPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        dataPanel = new javax.swing.JPanel();
        modelNamePanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        moveUpButton = new javax.swing.JButton();
        moveDownButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2));
        basicPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("<html>This model is linked form another model. <br> Modifications on this model<br>will also effect the other model.</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        jPanel1.add(jLabel1, gridBagConstraints);

        editButton.setText("edit");
        editButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(editButton, gridBagConstraints);

        deleteButton.setText("delete");
        deleteButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(deleteButton, gridBagConstraints);

        dataPanel.setLayout(new java.awt.BorderLayout());

        dataPanel.setBorder(new javax.swing.border.EtchedBorder());
        dataPanel.setMinimumSize(new java.awt.Dimension(200, 33));
        dataPanel.setPreferredSize(new java.awt.Dimension(200, 33));
        modelNamePanel.setText("jLabel2");
        dataPanel.add(modelNamePanel, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(dataPanel, gridBagConstraints);

        basicPanel.add(jPanel1, java.awt.BorderLayout.WEST);

        add(basicPanel, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.GridBagLayout());

        moveUpButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        moveUpButton.setMaximumSize(new java.awt.Dimension(35, 35));
        moveUpButton.setMinimumSize(new java.awt.Dimension(35, 35));
        moveUpButton.setPreferredSize(new java.awt.Dimension(35, 35));
        moveUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveUpButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(moveUpButton, gridBagConstraints);

        moveDownButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        moveDownButton.setMaximumSize(new java.awt.Dimension(35, 35));
        moveDownButton.setMinimumSize(new java.awt.Dimension(35, 35));
        moveDownButton.setPreferredSize(new java.awt.Dimension(35, 35));
        moveDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveDownButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(moveDownButton, gridBagConstraints);

        jPanel2.add(jPanel6, java.awt.BorderLayout.NORTH);

        add(jPanel2, java.awt.BorderLayout.WEST);

    }//GEN-END:initComponents

    private void moveDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveDownButtonActionPerformed
        this.unitPanel.moveModelDown(this.model, this);
    }//GEN-LAST:event_moveDownButtonActionPerformed

    private void moveUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveUpButtonActionPerformed
        this.unitPanel.moveModelUp(this.model, this);
    }//GEN-LAST:event_moveUpButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        this.unitPanel.removeLinked(this);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        this.basicPanel.removeAll();
        ArmylistEditorModelPanel panel = new ArmylistEditorModelPanel(this.model, this.unitPanel, this);
        this.unitPanel.linkedModelExpanded(panel);
        this.basicPanel.add(panel);
        this.basicPanel.updateUI();
    }//GEN-LAST:event_editButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basicPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel modelNamePanel;
    private javax.swing.JButton moveDownButton;
    private javax.swing.JButton moveUpButton;
    // End of variables declaration//GEN-END:variables
    
}
