/*
 * RosterGeneratorMainWindow.java
 *
 * Created on 04 December 2003, 17:34
 */

package plugins_src.org.jarmytoolplugins.newrostergenerator.guiComponents;

import org.jarmytoolplugins.newarmylisteditorplugin.util.VerticalFlowLayout;
import org.jarmytoolplugins.newrostergenerator.engine.RosterGeneratorCore;

/**
 *
 * @author  pasi
 */
public class RosterGeneratorMainWindow extends javax.swing.JFrame {
    
    private RosterGeneratorPreviewPanel preview;
    
    private RosterGeneratorCore core;
    
    /** Creates new form RosterGeneratorMainWindow */
    public RosterGeneratorMainWindow(RosterGeneratorCore core) {
        this.core = core;
        
        initComponents();
        this.controlsPanel.setLayout(new VerticalFlowLayout(0));
        this.preview = new RosterGeneratorPreviewPanel();
        this.previewPanel.add(this.preview);
    }
    
    public void setDocument(StringBuffer text){
        this.preview.setDocument(text);
    }
    
    public void setLaunchBrowserDisabled(boolean disabled){
        this.launchBrowserButton.setEnabled(!disabled);
    }
    
    public void copyAll(){
        this.preview.copyAll();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        controlsPanel = new javax.swing.JPanel();
        htmlControlPanel = new javax.swing.JPanel();
        regenerate = new javax.swing.JButton();
        writeHTMLButton = new javax.swing.JButton();
        launchBrowserButton = new javax.swing.JButton();
        bbCodeControl = new javax.swing.JPanel();
        regenerateBBCode = new javax.swing.JButton();
        copyBBCodeButton = new javax.swing.JButton();
        textControlPanel = new javax.swing.JPanel();
        generateTextButton = new javax.swing.JButton();
        writeTextButton = new javax.swing.JButton();
        copyTextButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        previewPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(150);
        controlPanel.setLayout(new java.awt.BorderLayout());

        htmlControlPanel.setLayout(new java.awt.GridBagLayout());

        htmlControlPanel.setBorder(new javax.swing.border.TitledBorder("HTML"));
        regenerate.setText("Generate");
        regenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regenerateActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        htmlControlPanel.add(regenerate, gridBagConstraints);

        writeHTMLButton.setText("Write to Disk");
        writeHTMLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeHTMLButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        htmlControlPanel.add(writeHTMLButton, gridBagConstraints);

        launchBrowserButton.setText("Launch Browser");
        launchBrowserButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        launchBrowserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchBrowserButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        htmlControlPanel.add(launchBrowserButton, gridBagConstraints);

        controlsPanel.add(htmlControlPanel);

        bbCodeControl.setLayout(new java.awt.GridBagLayout());

        bbCodeControl.setBorder(new javax.swing.border.TitledBorder("BBCode"));
        regenerateBBCode.setText("Generate");
        regenerateBBCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regenerateBBCodeActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        bbCodeControl.add(regenerateBBCode, gridBagConstraints);

        copyBBCodeButton.setText("Copy");
        copyBBCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyBBCodeButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        bbCodeControl.add(copyBBCodeButton, gridBagConstraints);

        controlsPanel.add(bbCodeControl);

        textControlPanel.setLayout(new java.awt.GridBagLayout());

        textControlPanel.setBorder(new javax.swing.border.TitledBorder("Text"));
        generateTextButton.setText("Generate");
        generateTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateTextButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        textControlPanel.add(generateTextButton, gridBagConstraints);

        writeTextButton.setText("Write to Disk");
        writeTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeTextButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        textControlPanel.add(writeTextButton, gridBagConstraints);

        copyTextButton.setText("Copy");
        copyTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyTextButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        textControlPanel.add(copyTextButton, gridBagConstraints);

        controlsPanel.add(textControlPanel);

        controlPanel.add(controlsPanel, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(controlPanel);

        jPanel3.setLayout(new java.awt.BorderLayout());

        previewPanel.setLayout(new java.awt.BorderLayout());

        jPanel3.add(previewPanel, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Preview:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel5.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel2.setText("(Preview shown here probably vary from the exported HTML but it gives some indication)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel5.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel3.setText("<html>To print the roster open it with a browser.</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel5.add(jLabel3, gridBagConstraints);

        jPanel4.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel3.add(jPanel4, java.awt.BorderLayout.NORTH);

        jSplitPane1.setRightComponent(jPanel3);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void copyTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyTextButtonActionPerformed
        this.core.copyText();
    }//GEN-LAST:event_copyTextButtonActionPerformed

    private void copyBBCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyBBCodeButtonActionPerformed
        this.core.copyBBCode();
    }//GEN-LAST:event_copyBBCodeButtonActionPerformed

    private void writeTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeTextButtonActionPerformed
        this.core.writeText();
    }//GEN-LAST:event_writeTextButtonActionPerformed

    private void generateTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateTextButtonActionPerformed
        this.core.generateText();
    }//GEN-LAST:event_generateTextButtonActionPerformed

    private void regenerateBBCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regenerateBBCodeActionPerformed
        this.core.generateBBCode();
    }//GEN-LAST:event_regenerateBBCodeActionPerformed

    private void launchBrowserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchBrowserButtonActionPerformed
        this.core.launchBrowser();
    }//GEN-LAST:event_launchBrowserButtonActionPerformed

    private void writeHTMLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeHTMLButtonActionPerformed
        this.core.writeHTML();
    }//GEN-LAST:event_writeHTMLButtonActionPerformed

    private void regenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regenerateActionPerformed
        this.core.regenerateHTML();
    }//GEN-LAST:event_regenerateActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
    }//GEN-LAST:event_exitForm
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bbCodeControl;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JButton copyBBCodeButton;
    private javax.swing.JButton copyTextButton;
    private javax.swing.JButton generateTextButton;
    private javax.swing.JPanel htmlControlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton launchBrowserButton;
    private javax.swing.JPanel previewPanel;
    private javax.swing.JButton regenerate;
    private javax.swing.JButton regenerateBBCode;
    private javax.swing.JPanel textControlPanel;
    private javax.swing.JButton writeHTMLButton;
    private javax.swing.JButton writeTextButton;
    // End of variables declaration//GEN-END:variables
    
}
