/*
 * RosterGeneratorPreviewPanel.java
 *
 * Created on 04 December 2003, 17:34
 */

package org.jarmytoolplugins.newrostergenerator.guiComponents;

import java.lang.StringBuffer;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author  pasi
 */
public class RosterGeneratorPreviewPanel extends javax.swing.JPanel {
    
    private HTMLEditorKit editorKit;
    
    /** Creates new form RosterGeneratorPreviewPanel */
    public RosterGeneratorPreviewPanel() {
        initComponents();
        this.editorKit = new HTMLEditorKit();
        this.previewEditor.setEditorKit(this.editorKit);
    }
    
    public void setDocument(StringBuffer text){
        this.previewEditor.setText(text.toString());
    }
    
    public void copyAll(){
        this.previewEditor.selectAll();
        this.previewEditor.copy();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        previewEditor = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(previewEditor);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane previewEditor;
    // End of variables declaration//GEN-END:variables
    
}
